### PR TITLE
Remove `layout: icon` from frontmatter as it's not needed

### PR DESCRIPTION
**Pull request by coliff**

### CODE REVIEW

**Comment by XhmikosR** [comment]
When we initially set up Hugo, we didn't make proper use of the template hierarchy hence this key.

BTW, feel free to tweak our layouts more. Ideally, we should follow the hierarchy and eventually offer tag and category pages later :)

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
We don't have a Cloudflare Pages preview, but the change LGTM. We can always revisit if something breaks.

**Comment by coliff** [comment]
> BTW, feel free to tweak our layouts more. Ideally, we should follow the hierarchy and eventually offer tag and category pages later :)

Yep, I'd be happy to help out a bit more on the site side of things. I think it'd be great to get #731 finished and merged. I was thinking that being able to click on the category name from each icon page could then show the filtered search results. e.g.
https://icons.getbootstrap.com/?category=arrows

**Comment by korki43** [comment]
> I think it'd be great to get #731 finished and merged.

We are waiting for #706 to be finished. There are still some open points to discuss there.

**Pull request merged**
