### PR TITLE
CI: Fix deploy script

### PR DESCRIPTION
**Pull request by XhmikosR**
This should work, at least in theory. I think the previous behavior would fire if one pushed to a tag, which isn't what we want.

**Untested, though.**

PS. There's a `prereleased` event too, not sure if we want also to consider this: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release
PPS. Another solution would be to use `if: startsWith(github.ref, 'refs/tags/')` in the job. We use this on https://github.com/mdo/github-buttons/blob/c4f1c6835d8353ba0b2663de3bfa871fb0d5cafb/.github/workflows/ci.yml#L50
PPPS: I guess we could move the deploy job to the CI workflow and just do the aforementioned?

### CODE REVIEW

**Review by mdo — APPROVED** [review]
Looks good to me. Going to try it with v1.2.2.

**Comment by XhmikosR** [comment]
Let me know if you want me to go with the other suggested solution. It should result in faster deployments since we'd build everything once, but it's not a huge deal since deployments aren't that frequent. And we can change this later if needed.

**Comment by mdo** [comment]
Worked great!

**Comment by XhmikosR** [comment]
I'll have another take at it when I have some time :)

**Pull request merged**
