### PR TITLE
34 new icons, plus some renames

### LINKED ISSUE #104: [icon request] empty octagon shape
Icon request for `octagon` and `octagon-fill` (and maybe `octagon-half` to be consistent with the other basic shape icons) :

image

### LINKED ISSUE #109: [icon request] double chevron icons
Currently there are single chevron icons, but it would be nice to have double chevron icons as well.

### PR DESCRIPTION
**Pull request by mdo**
**Requires a base branch change before merging!**

---

This PR will come after #137 is merged as it's built on that PR.

- New: octagon, octagon-half, octagon-fill (fixes #104)
- New: clipboard, clipboard-data
- New: layers, layers-half, layers-fill
- New: briefcase
- New: double chevrons (chevron-double-down, chevron-double-left, chevron-double-right, chevron-double-up) (fixes #109)
- New: funnel, funnel-fill
- New: grid-1x2, grid-1x2-fill
- New: grid-3x2-gap, grid-3x2-gap-fill
- New: grid-3x2
- New: grid-3x3
- New: graphics glyphs (exclude, intersect, subtract, union, circle-square)
- New: layout-sidebar-nested
- New: layout-three-columns
- New: layout-wtf
- New: newspaper
- New: paperclip
- New: people-circle
- New: diamond, diamond-fill
- Renamed: columns-gutters to columns-gap
- Renamed: diamond to gem, because diamond shapes
- Fixed: document-* classes changed to file-* to match the rename from #137

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo it seems this branch has unrelated changes like the content changes

**Comment by XhmikosR** [comment]
Here is the branch rebased from master, with `npm run icons` run https://github.com/twbs/icons/tree/alpha3-new-icons-xmr

If it looks good to you let me know so that I force push the branch to this one so that we aren't blocked by #137

**Comment by mdo** [comment]
Yeah, this branch is targeted against #137 and was meant to come after that one is merged, hence the permalink pages here. I don't want to give up on the permalink pages landing just yet—I'm fine with the approach there for now and we can iterate on it in other releases if needed. Haven't gotten any feedback yet on #137.

**Comment by XhmikosR** [comment]
TBH I don't want to hurry this until we hear from @regisphilibert who's basically one of the Hugo gurus out there I know and I trust :)

So, my suggestion would be to untie this PR from #137 and land it, after we wait a few more days in case #137 is solved.

I know #137 works, but the amount of stuff it adds is just too much to hurry this, especially if we can just automate it somehow natively.

In the end it's your call, just my 2 cents :)

**Comment by XhmikosR** [comment]
Although, I have to admin, I have no idea how to handle the categories and
keywords. The rest could be somehow generated from the filenames, but for
the rest we'd need to add the data some way.

So, I suggest wait a bit until I review the other PR, we merge it and see
if we can simplify later.

Still, I'd like to get the layouts hierarchy right regardless.

**Comment by mdo** [comment]
Closing for #137 and #149, which I opened and merged to get just the SVGs in. Moving the rest to the `icon-pages` branch. Thanks for the feedback, @XhmikosR!

**Comment by tmorehouse** [comment]
Would it be possible, at build time, to generate a JSON file with the icons names as keys, and meta date (categories, etc) and properties?

**Pull request closed without merging**
