### PR TITLE
Update svgo to v2.3.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
@mdo this should be ready. I cleaned up our svgo config while at it.

The only "downside" could be that svg-sprite is using svgo 1.x. I might take a stab at updating to 2.x on our svg-sprite fork and thus simplify and make #340 consistent in the next days.

Preview: https://deploy-preview-758--bootstrap-icons.netlify.app/

### CODE REVIEW

**Comment by XhmikosR** [comment]
[v2.2.0](https://github.com/svg/svgo/releases/tag/v2.2.0) has some further fixes and the individual SVGs are modified. Might be worth importing the original files and running `npm run icons-main` to get the latest fixes.

**Review by leyla559 — APPROVED** [review]

**Comment by XhmikosR** [comment]
Some more insight from svgo's 2.x [docs](https://github.com/XhmikosR/svgo#configuration):

>The default list is fully overridden if the `plugins` field is specified. To extend the default list use the `extendDefaultPlugins` utility:
>
>```js
>const { extendDefaultPlugins } = require('svgo');
>module.exports = {
>  plugins: extendDefaultPlugins([
>    {
>      name: 'builtinPluginName',
>      params: {
>        optionName: 'optionValue'
>      }
>    }
>  ])
>}
```

**Review by mdo — APPROVED** [review]

**Comment by mdo** [comment]
@XhmikosR I did a fresh export from Figma, then re-ran the script, and pushed the difference. ~50 icons had small changes.

**Comment by XhmikosR** [comment]
Some icons were wrong like union.svg :P

I'll quickly review later and merge.

**Pull request merged**
