### PR TITLE
add icon & page: remove-formatting

### PR DESCRIPTION
**Pull request by miaochenxi**
fixed issue: #385 which requests an icon

### CODE REVIEW

**Comment by miaochenxi** [comment]
shot

**Comment by psjishnu** [comment]
@miaochenxi 

screen


Can you please mention why is not visible in home page .

The deployed preview of your PR . https://deploy-preview-392--bootstrap-icons.netlify.app/

**Comment by miaochenxi** [comment]
> @miaochenxi
> 
> screen
> 
> Can you please mention why the remove-formatting icon is not visible in home page .
> 
> The deployed preview of your PR . https://deploy-preview-392--bootstrap-icons.netlify.app/

uhh,idk why.
I even try to copy the existing icon and run the npm scripts,and it is not visible either,now still finding solution

**Comment by miaochenxi** [comment]
shot
@psjishnu fixed :D, i forgot to add the icon to bootstrap-icons.svg, now it's visible in the home page

**Pull request closed without merging**
