### PR TITLE
Reorganize layouts

### PR DESCRIPTION
**Pull request by inwardmovement**
Following https://github.com/twbs/icons/pull/170

### CODE REVIEW

**Comment by mdo** [comment]
@inwardmovement Thanks for this! I've been coming up short on trying to get category and tag pages to work in the Icons. Any ideas what I'm missing? I'm still getting familiar with Hugo.

**Comment by inwardmovement** [comment]
I'll have a look, but maybe you should start by removing [taxonomy/taxonomyTerm](https://gohugo.io/content-management/taxonomies#default-taxonomies) from the [config](https://github.com/twbs/icons/blob/master/config.yml#L7)

**Comment by inwardmovement** [comment]
Removing `taxonomy` causes an error, it seems to mess with the "icons" taxonomy manually created:
```
executing "partials/icons.html" at <$.Site.GetPage>: error calling GetPage: page reference "/alarm" is ambiguous
```

I'm still getting to know Hugo too, for now I don't know how to get around this quickly, maybe XhmikosR has an idea, or bep/someone at Hugo.

On the other side removing `taxonomyTerm` then allows you to go to `/tags/key/` for example and get all icons tagged `key`:
image

**Comment by XhmikosR** [comment]
@inwardmovement thanks for the PR again! Feel free to open a new one. I plan to switch to a baseof template, and enable taxonomies and terms so any help is welcome.

I've made a few tweaks and after #729 there shouldn't be any further errors with taxonomy and terms enabled.

**Pull request closed without merging**
