### PR TITLE
Prep for v1.3.0

### PR DESCRIPTION
**Pull request by mdo**
- Bump versions
- Update preview
- Update Figma link

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo when you run `npm icons` don't you get modified fonts locally? Make sure you do `npm i` before running the script in this branch. I keep getting modified fonts locally.

```
C:\Users\xmr\Desktop\bootstrap-icons>npm run icons

> bootstrap-icons@1.2.2 icons C:\Users\xmr\Desktop\bootstrap-icons
> npm-run-all icons-main --parallel icons-sprite icons-font


> bootstrap-icons@1.2.2 icons-main C:\Users\xmr\Desktop\bootstrap-icons
> node build/build-svgs.js

[build-svgs.js] started

Success, 1265 icons prepared!
[build-svgs.js] finished: 3.760s

> bootstrap-icons@1.2.2 icons-font C:\Users\xmr\Desktop\bootstrap-icons
> fantasticon


> bootstrap-icons@1.2.2 icons-sprite C:\Users\xmr\Desktop\bootstrap-icons
> svg-sprite --svg-namespace-classnames false --symbol --symbol-dest . --symbol-sprite bootstrap-icons.svg icons/*.svg

Generating font kit...
✔ Using configuration file: .fantasticonrc.js
✔ 1265 SVGs found in ./icons
✔ Generated ./font/fonts/bootstrap-icons.woff
✔ Generated ./font/fonts/bootstrap-icons.woff2
✔ Generated ./font/bootstrap-icons.css
✔ Generated ./font/bootstrap-icons.json
✔ Generated ./font/index.html
Done

C:\Users\xmr\Desktop\bootstrap-icons>git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   font/fonts/bootstrap-icons.woff
        modified:   font/fonts/bootstrap-icons.woff2

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by mdo** [comment]
Yes the fonts regen every single run. I opened #618 for that.

**Comment by XhmikosR** [comment]
Not that it runs but that the generated files seem modified?

**Comment by XhmikosR** [comment]
OK, NVM, I now see the issue. I thought you just missed updating the files. I'll have a closer look, but it might be a bug in fantasticon

**Comment by XhmikosR** [comment]
@mdo the preview image is starting to get too big. Not sure what we can do, though... Unless, we didn't show all the icons in the preview?

**Pull request merged**
