### PR TITLE
added phone-fill . Fixed Issue #211

### PR DESCRIPTION
**Pull request by psjishnu**

### CODE REVIEW

**Comment by psjishnu** [comment]
Solved Issue #211 . Added phone-fill

**Comment by psjishnu** [comment]
screen

**Comment by psjishnu** [comment]
Phone Landscape fill
screen

**Comment by psjishnu** [comment]
@XhmikosR  Can you please review the PR 🙂 .

**Comment by XhmikosR** [comment]
Sorry, the icons are @mdo's area :)

**Comment by psjishnu** [comment]
@mdo Requesting review for PR 🙂.

**Comment by mdo** [comment]
This is being addressed in Figma first, and has been included in #273. Thanks though!

**Pull request closed without merging**
