### PR TITLE
Icon link set to open in same tab(commit to 'main)

### PR DESCRIPTION
**Pull request by arya-vats**
Earlier the icons link was opening on to a new tab due to the _blank target. I have set it to _self to open in the same tab.

Please see the updated code.

Thank You!

### CODE REVIEW

**Review by arya-vats — COMMENTED** [review]
.

**Review by coliff — COMMENTED** [review]
- You don't need `target="_self"` if the link will open in the same tab.
- I don't think you should change the behaviour of the Themes link which opens in a new tab.
- PRs should only have 1 commit so you should squash your 3 commits.

**Comment by arya-vats** [comment]
That was really helpful sir!
Thanks a lot.
As i am new to open source , can you please suggest any changes in my pr?

**Comment by coliff** [comment]
> can you please suggest any changes in my pr

I think the PR simply needs to remove `target="_blank"` from the icon link in the navbar (with no other changes) and it should be a single commit.

**Comment by mdo** [comment]
#1329

**Pull request closed without merging**
