### PR TITLE
Update check-icons.js

### PR DESCRIPTION
**Pull request by XhmikosR**
* return early
* use `path.basename` and `path.extname`
* replace `require` with `fs.readFile`
* move variables

@korki43 could you check this one too please? https://github.com/twbs/icons/pull/1660/files?w=1

### CODE REVIEW

**Comment by XhmikosR** [comment]
@korki43 could you check this one too please? https://github.com/twbs/icons/pull/1660/files?w=1

**Review by korki43 — COMMENTED** [review]
LGTM! I like the early return statement.

**Review by korki43 — COMMENTED** [review]
You could pull the `process.exit()` out of the if-statements, so it doesn't stop after only showing the wrong icons in the JSON file. Theoretically you could also replace it with a `throw` statement, like in my original PR, but I don't see the advantages to logging an additional error after already showing the wrong icons.

**Comment by XhmikosR** [comment]
> You could pull the `process.exit()` out of the if-statements, so it doesn't stop after only showing the wrong icons in the JSON file.

You might be right there, it maybe make more to just exit at the end once with `process.exit(1)`. I will try it, thanks :)

> Theoretically you could also replace it with a `throw` statement, like in my original PR, but I don't see the advantages to logging an additional error after already showing the wrong icons.

Yeah, that didn't work, unfortunately that's why I removed it.

If you make any progress feel free to PR, thanks! :)

**Comment by XhmikosR** [comment]
I replaced `require` with `fs.readFile` since the former doesn't work with `modules` (not that we will switch anytime soon, but it's future-proof 🙂)

**Pull request merged**
