### PR TITLE
add copy icon slug to single/home templates

### PR DESCRIPTION
**Pull request by inwardmovement**
closes https://github.com/twbs/icons/issues/298

### CODE REVIEW

**Comment by inwardmovement** [comment]
@XhmikosR The home part is a bit inelegant but it seems to work as I imagined.
Do you think the extra tab stop with keyboard navigation is annoying?

**Comment by XhmikosR** [comment]
Doesn't look bad!

Please don't rebase/merge so regularly because we are notified each time. Someone will take a look and we'll let you know :)

**Comment by XhmikosR** [comment]
@mdo what's your take on this?

**Comment by inwardmovement** [comment]
Maybe we could add a paragraph below the heading that says something like "Useful when dynamically importing the SVG".

**Comment by XhmikosR** [comment]
I don't think we need more things in the homepage TBH. The homepage is already too bloated and even this change might be too much with the current state of things.

If we eventually split it, it should be easier.

Another thing we could do is show the copy on hover but it's bad for mobile and not sure about a11y either.

Let's wait to hear if @mdo likes this approach and we'll see how to proceed :)

**Comment by inwardmovement** [comment]
> I don't think we need more things in the homepage

I meant on the single page

**Pull request closed without merging**
