### PR TITLE
Generate font page with Hugo

### PR DESCRIPTION
**Pull request by XhmikosR**
~~This is for preview purposes currently. We first need to finish with the other PRs.~~

TODO:

- [x] Finish with the other PRs
- [x] Fill description and title
- [x] Include ads in the layout?
- [x] Add the font page in a subnav or something? Currently, I have added breadcrumbs only, but the page is not linked from anywhere else
- [x] If needed, manually clean up the patches before merging

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo this is mostly ready from my side. I need some help with the remaining TODOs from you

**Comment by XhmikosR** [comment]
@mdo we should really move with this; it saves us a lot of duplication and currently it's also blocking #824.

**Comment by korki43** [comment]
Is an explicit font page really necessary? Isn't it just showing the same as the homepage? I can't really see a use case for this.

I also think that we should try to document the code points properly (#891). They could be included on this page or on the page of an icon.

**Comment by XhmikosR** [comment]
Well, compared to the crappy looking page we have right now, this looks better. This page serves as a test page to make sure the font is fine too.

**Pull request merged**
