### PR TITLE
Remove incorrect bi from i usage

### PR DESCRIPTION
**Pull request by fulldecent**
This PR removes the extra `bi` in the `<i>` usage examples:

```diff
- <i class="bi bi-%s"></i>
+ <i class="bi-%s"></i>
```

Documentation on the [main page](https://icons.getbootstrap.com/) says to use `<i class="bi-alarm"></i>` which does not have `bi`. But documentation on the [inner pages](https://icons.getbootstrap.com/icons/alarm/) adds an extra `bi`.

This is a problem because using the extra `bi` in this scenario causes a layout problem.

Minified test case showing the problem with extra `bi`:

https://stackblitz.com/edit/zjw8ha?file=index.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Layout issue</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" integrity="sha256-2IJPcGfN/qOK/sfp/68HISUmaCQgbWnvHxEtchU6UF4=" crossorigin="anonymous">
  </head>
  <body class="p-5">
    <p>
      <a class="icon-link"><i class="bi-receipt"></i> Correct</a>
    </p>

    <p>
      <a class="icon-link"><i class="bi bi-receipt"></i> Incorrect</a>
    </p>
  </body>
</html>
```

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo I'll defer this to you

**Comment by XhmikosR** [comment]
Ah that's the markup for the docs not the rendered one.

**Comment by fulldecent** [comment]
@XhmikosR no, no please see here

Screenshot 2023-11-01 at 17 42 49

**Comment by XhmikosR** [comment]
What you see in your screenshot is the correct result, there's nothing to change here.

**Comment by fulldecent** [comment]
Okay, I moved this back to an issue to more clearly illustrate the problem

https://github.com/twbs/icons/issues/1878

**Pull request closed without merging**
