### PR TITLE
Stop generating font JSON file

### PR DESCRIPTION
**Pull request by XhmikosR**
We don't use it, unsure if any consumers of the package use it?

### CODE REVIEW

**Comment by mdo** [comment]
I think we're good to keep it around for a bit since it'd be a breaking change if someone _were_ using it.

**Comment by XhmikosR** [comment]
Technically, yeah, it could be a breaking change, but I'm not sure when v2.0 might happen :P

I'd just try to do it in a minor release and if we get any reports of people missing it, we can add it back.

About your second point, I'm not sure it's doable and it would require quite a lot of refactoring, so that may never happen. I mean, yea, we could have leafless bundles, but I've never used this feature yet with Hugo.

**Comment by mdo** [comment]
Maybe we close given #814?

**Comment by XhmikosR** [comment]
Yeah, if we are going to use the JSON file, for sure.

**Pull request closed without merging**
