### PR TITLE
build: switch to modules

### PR DESCRIPTION
**Pull request by XhmikosR**
@korki43 do you have any opinion? Modules are inherently faster :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
The reason I went with mjs is so that we don't need to specify `"type": "module"` in package.json. I don't like mjs either but I don't think there's another way to do it?

**Comment by korki43** [comment]
Yes, I agree. After all these are just a few build scripts so changing the whole projects module system wouldn't be a good idea.

**Comment by XhmikosR** [comment]
Cool, I'll try to do the same changes in the bootstrap repo and then land this one :)

**Comment by XhmikosR** [comment]
I'll revisit this when I'm done with the upstream changes so that we have the same point of reference.

**Pull request merged**
