### PR TITLE
v1.11.0 Icons

### LINKED ISSUE #271: Cake icon
Please add **cake** icon, we associate it with birthday. Something similar to the one found in [fontawesome](https://fontawesome.com/icons/birthday-cake?style=solid)

### LINKED ISSUE #272: Save (floppy disk) icon
Please add an icon representing **save**. Something similar to the one in [fontawesome](https://fontawesome.com/icons/save?style=regular)

### LINKED ISSUE #410: figma file can't open
I can't open this figma file 
https://www.figma.com/file/9YmlUAwhMv99G4yP4yN7Jy/Bootstrap-Icons-v1.0.0?node-id=0%3A1

### LINKED ISSUE #442: Ban Icon does not convey the message it should
Hi, I was trying to migrate to bootstrap icons and found that ban icon is very strange compared to the other libraries, the slash should cover the entire circle, not cut where it does, I've done User Interviews and none of them understand your variant.

What do you think about changing it or builing another icon? 

Here is an example:
image

### LINKED ISSUE #595: The news headline on the site does not lead to the latest release
Hello, on your [website ](https://icons.getbootstrap.com/) on label header old version. The link does not lead to the last blog post. This is a minor and non-critical bug. I wish you a good Christmas.
image

**Expected Behavior:**
image

### LINKED ISSUE #653: arrows-h-expand / arrows-h-collapse
Would you please consider providing horizontal alternatives to existing arrows-expand & arrows-collapse  ?
similar to https://fontawesome.com/icons/arrows-alt-h

Thanks!

### LINKED ISSUE #712: Cookie icon
It would be great, if you could add an icon related to cookies. It would make cookie consent dialogs more playful. Thanks

### LINKED ISSUE #713: Add feather icon
please add feather icon

Thanks in advance.

### LINKED ISSUE #778: Beaker icon
I can't seem to find a `beaker` icon, representing experiments, tests etc

First result on Google:
image

### LINKED ISSUE #785: Please add GitLab icon
Please add a GitLab icon.

The official SVG can be found at: https://about.gitlab.com/press/press-kit/

### LINKED ISSUE #956: highlight icon
A marker icon (highlight), can be used in a text editor
for example
image

### LINKED ISSUE #973: add birthday icon

### LINKED ISSUE #1001: Copy-Paste icon
There seems to be no copy-paste icon available.
There's clipboard-plus and clipboard-minus, but no icon for copy-paste (in one motion).

There's also no icon for file-copy (or duplicate).

### LINKED ISSUE #1474: Crosshairs
It's really useful when you want to change the mode the mouse is operating to pick a given element, and much less ambiguous than the bullseye which is not the standard mouse cursor for that situation.

Example of a crosshairs icon:
https://fontawesome.com/v4/icon/crosshairs

### LINKED ISSUE #1480: Chat sent / received
There already are many contextual chat / conversation / message icons - speech bubbles with extra content within.

But two important ones are missing, which would be very helpful:
- one for sent / initiated / started
- one for received
 
Typically these are shown as speech bubbles with up and down arrows.

Examples [from fontawesome](https://fontawesome.com/search?q=chat%20arrow&o=r).

Thank you.

### LINKED ISSUE #1537: Wheelchair icon
Something similar like this:
https://www.flaticon.com/free-icon/wheelchair_657563?term=handicapped&page=1&position=2&page=1&position=2&related_id=657563&origin=search

### LINKED ISSUE #1584: Opacity Logo
A logo to show "Opacity" or "Transparency".

Something like this:

image
image
image
image
image

### LINKED ISSUE #1665: Brand Request: sourceforge
Please add a Sourceforge.net icon
https://sourceforge.net/

### LINKED ISSUE #1700: Icon request: Substack
[https://substack.com/] is a service for newsletter, news, and recently a twitter like note system. 

Official brand assets can be found [here](https://substack.com/brand)

### LINKED ISSUE #1716: Passport icon
https://www.svgrepo.com/vectors/passport/ add passport icon

### LINKED ISSUE #1717: Please add a neuter gender icon
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please consider adding a neuter gender icon. Something similar to Font Awesome Icons nice and straightforward https://fontawesome.com/v4/icon/neuter.

### Motivation and context

I use Bootstrap Icons on a educational website for Russian language. Words in that language, like in many other languages, can be of three genders -- masculine, feminine, and neuter. While `gender-female` and `gender-male` icons perfectly suit first two, there is nothing appropriate to represent the neuter gender without sliding into modern gender craze. Thank you.

### LINKED ISSUE #1741: Icon request: Type variants for H4, H5 and H6
Type variants for H4, H5 and H6, just like: [type-h1](https://icons.getbootstrap.com/icons/type-h1/)

### LINKED ISSUE #1744: Icon request: Travel Equipment (Suitcase, luggage, backpack)

### LINKED ISSUE #1750: Clone Icone
Please add icon for clone

https://www.svgrepo.com/vectors/clone/

### LINKED ISSUE #1752: Threads Icon
New Twitter like app called Threads by Meta/Facebook. Hopefully this logo can get an Icon.

https://en.wikipedia.org/wiki/Threads_%28app%29

### LINKED ISSUE #1753: Icon request: Open Collective

### LINKED ISSUE #1765: Add Bing (Search Engine) Icon
There's already an icon for `Google`, but we're still missing an icon for `Bing`. 

Here's how the Bing logo looks:
Bing Logo

### LINKED ISSUE #1770: abc & ABC (Icons Request)
We already have a `123` icon: https://icons.getbootstrap.com/icons/123/

Can we please get `abc` and `ABC` icons too?

### LINKED ISSUE #1771: Person Standing Icon
I want an icon where there is a person that is simply standing.

Something like:

Person Standing Icon
Person Standing Icon

### LINKED ISSUE #1772: Person Walking Icon
I want an icon of a person walking left or right.

Something like:

Person Walking Icon
Person Walking Icon
Person Walking Icon

### LINKED ISSUE #1774: No Sim (Simcard) icon
I know we already got two simcard icons:

image

But there isn't an icon to indicate no simcard. Like when a simcard is missing or not properly inserted.

Can we please get an icon for that?

Here are some examples:

No Sim (Simcard) icon
No Sim (Simcard) icon
No Sim (Simcard) icon
No Sim (Simcard) icon

### LINKED ISSUE #1778: Twitter rebranded
According to twitter rebranding to x this new icon will be needed.

### PR DESCRIPTION
**Pull request by mdo**
### Updated
- Fixes #1741: Redrew parts of type-h1, type-h2, type-h3 to be more pixel perfect head of new h4, h5, h6 variants

### New

- Fixes #271
- Fixes #410
- Fixes #442
- Fixes #595
- Fixes #653
- Fixes #712
- Fixes #713
- Fixes #778
- Fixes #785
- Fixes #956
- Fixes #973
- Fixes #1001
- Fixes #272
- Fixes #1474
- Fixes #1480
- Fixes #1537
- Fixes #1584
- Fixes #1665
- Fixes #1700
- Fixes #1741
- Fixes #1750
- Fixes #1752
- Fixes #1753
- Fixes #1765
- Fixes #1770
- Fixes #1774
- Fixes #1778
- Fixes #1716
- Fixes #1717
- Fixes #1744
- Fixes #1771
- Fixes #1772

### CODE REVIEW

**Comment by Aworldc** [comment]
Woooooo we have a floppy save!!!! 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by HarisSpahija** [comment]
Is there any way we can help with this PR? Cant wait for the new icons 🎉

**Comment by mdo** [comment]
Just wrapped up the remaining icons. Have to create the pages next, then can handle a release. Hang tight!

**Comment by shaunroselt** [comment]
This is a great release.

Thanks!

**Comment by Aworldc** [comment]
💾💾💾💾💾💾💾💾💾💾💾💾🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by femmor** [comment]
Please add food, drinks or meal icons to the library.

**Pull request merged**
