### PR TITLE
Accessibility tweaks/additions

### PR DESCRIPTION
**Pull request by patrickhlauke**
- add an accessibility section (to remind authors to provide a text alternative where non-decorative)
- minor tweaks to index and single page

### CODE REVIEW

**Comment by XhmikosR** [comment]
@patrickhlauke perhaps we should change the default font snippet in icons/single.html to include `aria-hidden="true"`?

**Comment by patrickhlauke** [comment]
> @patrickhlauke perhaps we should change the default font snippet in icons/single.html to include `aria-hidden="true"`?

no i think it's appropriate to signal it as an image, as that's the "raison d'etre" of that page...to show a big preview of the icon. so an AT user knows that there's an image there of the glyph.

**Comment by XhmikosR** [comment]
> no i think it's appropriate to signal it as an image, as that's the "raison d'etre" of that page...to show a big preview of the icon. so an AT user knows that there's an image there of the glyph.

I meant in the font snippet we are suggesting to users.

**Comment by patrickhlauke** [comment]
ah, on the right-hand "Copy HTML" bit? Well in theory, as long as there's no actual text inside the SVG, it should be transparent to assistive technologies - they won't announce anything there, as if it were a series of divs and spans with no content. And depending on how authors then use those, they may want to either keep it that way, *or* add `role="img" aria-label="..."`, but that depends a bit on their use case. I personally think it's fine to keep it as is just now...

**Review by XhmikosR — APPROVED** [review]

**Comment by patrickhlauke** [comment]
🚀

**Pull request merged**
