### PR TITLE
Adds a "style" field to package.json

### PR DESCRIPTION
**Pull request by ojvribeiro**
This allows us to use some auto import script, by exposing the main CSS file path.

### CODE REVIEW

**Comment by bram-pkg** [comment]
I have extended this to also include the `sass` field, like in `bootstrap`. 

https://github.com/twbs/icons/pull/1146

**Comment by mdo** [comment]
Duplicate of #1146.

**Comment by ojvribeiro** [comment]
Technically #1146 is a duplicate of this PR, but ok.

**Comment by bram-pkg** [comment]
Sorry to hijack your PR, it just also includes the SCSS field.

**Comment by mdo** [comment]
Yup, sorry, I could've been more accurate in my comment. Appreciate the PR regardless ❤️

**Pull request closed without merging**
