### PR TITLE
Add GitLab icon

### LINKED ISSUE #785: Please add GitLab icon
Please add a GitLab icon.

The official SVG can be found at: https://about.gitlab.com/press/press-kit/

### LINKED ISSUE #1009: Add Gitlab icon
Add GitLab logo

file:
https://about.gitlab.com/press/press-kit/

### LINKED ISSUE #1529: Matrix.org icon
https://en.wikipedia.org/wiki/File:Matrix_icon.svg

### PR DESCRIPTION
**Pull request by mrdrogdrog**
Add icon for Gitlab

Fixes #785

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mrdrogdrog thanks for the PR! Could please split this PR into two? I'm not sure the GitLab logo looks good, but I'll leave that for @mdo to judge.

So, better keep each icon in separate PRs.

**Comment by mrdrogdrog** [comment]
Done. See https://github.com/twbs/icons/pull/1650

**Comment by mrdrogdrog** [comment]
@XhmikosR any idea when my PRs will be reviewed or merged? :/

**Comment by XhmikosR** [comment]
Sorry, the new icons are mainly added by @mdo, so he'd need to have a look at your PRs.

**Pull request closed without merging**
